### ISSUE TITLE
Can this is updated to work with latest WCT 6.5.0?

### ISSUE THREAD

**Issue by jaichandra** [t2ym/web-component-tester-istanbul#3]

**Comment by t2ym** [comment]
@jaichandra It may be possible but with many tricks.

## Many tricks are required to make it work with WCT 6.5.0
- The new plugin hook `define:webserver` since WCT 6.4.1 is insufficient to insert source code transformers for coverage.  `t2ym/web-component-tester` is used instead to support a custom `wctPlugin` option for `t2ym/polyserve`.
- The official `polyserve` does not support insertion of transformers.  `t2ym/polyserve` is used instead.
- SauceLabs block large socket.io payloads.  `t2ym/web-component-tester/browser.js` hacks socket.io traffic to chop the socket.io payloads into 64KB chunks and `t2ym/web-component-tester` reassembles them.
- It is not easy to patch `browser.js` for the official `web-component-tester` at runtime.  Just replacing `browser.js` to a fixed custom version for `wct-istanbul` is possible but the version cannot automatically follow the official version.
- There may be other hindrances to overcome, which are not scoped.

## Notes
- Forks like `wct-istanbub`, which is replacing `polyserve` with another express web server serving local files directly and bypassing ES5 transpilation and other transformations by `polyserve`, are trying to work with WCT 6.4.1 and later.  Mapping to local files from URLs is not very straightforward in `polyserve`. They also have to overcome the above issues.
- For normal Polymer 2.x projects and elements, `@t2ym/web-component-tester@6.0.2` and `wct-istanbul@0.12.4` should be sufficient.
- `t2ym/polyserve` includes the `--npm` option, which has not been verified.

**Comment by jaichandra** [comment]
@t2ym Thanks for the detailed explanation.

**Comment by t2ym** [comment]
@jaichandra You can try [wct-istanbul@0.13.0](https://www.npmjs.com/package/wct-istanbul) with WCT 6.6.0 support with limitation on Sauce Labs

**Comment by t2ym** [comment]
Supported with `wct-istanbul@0.14.2`
